version: '3'

services: 
    angular:
        build: angular-client
        container_name: ecommerce-client
        ports:
            - "4200:4200"
            # - "49153:49153"
        volumes:
            - ./angular-client/:/var/www/app
            - /var/www/app/node_modules/

    express:
        build: express-server
        container_name: ecommerce-server
        restart: always
        ports:
            - "3000:3000"
        volumes:
            - ./express-server/:/var/www/app
            - /var/www/app/node_modules/
        depends_on:
            - mongodb
    
    mongodb:
        image: mongo
        container_name: ecommerce-db
        restart: always
        ports:
            - "27017:27017"
        volumes:
            - mydata:/data/db

    seeder:
        image: pkosiec/mongo-seeding:3.0.0
        volumes:
            - ./express-server/seeds/:/data-import
        working_dir: /data-import
        environment: 
            DB_URI: 'mongodb://mongodb/ecommerce'
            DROP_DATABASE: 'true'
        depends_on: 
            - mongodb

volumes:
    mydata: